let {
  PORT,
  MONGO_URI,
  JWT_SECRET,
  NODE_ENV,
  ORIGIN_URL,
  ENVIRONMENT,
  // PROD_PORT,
  // PROD_MONGO_URI,
  // PROD_JWT_SECRET,
  // PROD_ORIGIN_URL,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_BUCKET_NAME,
  STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET,
} = process.env;

const IN_PROD = NODE_ENV == "production";

// if (IN_PROD) {
//   PORT = PROD_PORT;
//   MONGO_URI = PROD_MONGO_URI;
//   JWT_SECRET = PROD_JWT_SECRET;
//   ORIGIN_URL = PROD_ORIGIN_URL;
// }

module.exports = {
  PORT,
  MONGO_URI,
  JWT_SECRET,
  ORIGIN_URL,
  NODE_ENV,
  IN_PROD,
  ENVIRONMENT,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_BUCKET_NAME,
  STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET,
};
